language: julia
os:
    - linux
    - osx
    - windows
julia:
    - release
sudo: false
notifications:
    email: false
    after_success:
    - julia -e 'cd(Pkg.dir("MolecularPDB")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'